version: '3'
 
services:

    nginx:
      image: nginx:1.17.8
      container_name: thyroid_nginx
      ports:
        - 8000:80
      volumes:
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        - ./www:/var/www/html
      depends_on:
        - php 
        - mysql 
      restart: always

    php:
      build: ./php
      container_name: thyroid_php
      volumes:
        - ./www:/var/www/html
        - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
      restart: always
    
    phpmyadmin: 
      image: phpmyadmin/phpmyadmin
      container_name: thyroid_phpmyadmin
      ports:
        - 8080:80
      environment:
        - PMA_ARBITRARY=1
        - PMA_HOST=thyroid_mysql
      depends_on: 
        - mysql 
      restart: always

    mysql:
      image: mysql:8.0.19
      container_name: thyroid_mysql
      volumes:
        - ./mysql:/var/lib/mysql
      environment:
        - MYSQL_DATABASE=mydb
        - MYSQL_ROOT_PASSWORD=123456
        - MYSQL_USER=thyroid
        - MYSQL_PASSWORD=123456
      ports:
        - 3308:3306
      restart: always


    

